const ErrorString = {
    //Restaurant
    RESTAURANT_NOT_FOUND: 'RESTAURANT NOT FOUND',
    UPDATE_RESTAURANT_SUCCESSFULLY: 'UPDATE RESTAURANT SUCCESSFULLY',
    DELETE_RESTAURANT_SUCCESSFULLY: 'DELETE RESTAURANT SUCCESSFULLY',

    //Admin
    APPROVE_POST_FAIL: 'APPROVE POST FAIL',  
    POST_APPROVED: 'POST APPROVED', 
};

module.exports = ErrorString;