const ResponseString = {
    //Restaurant
    RESTAURANT_NOT_FOUND: 'RESTAURANT NOT FOUND',
    UPDATE_RESTAURANT_SUCCESSFULLY: 'UPDATE RESTAURANT SUCCESSFULLY',
    DELETE_RESTAURANT_SUCCESSFULLY: 'DELETE RESTAURANT SUCCESSFULLY',

    //Admin
    POST_REJECTED: 'POST REJECTED',  
    POST_APPROVED: 'POST APPROVED', 

    //Order restaurant
    ORDER_RESTAURANT_REJECTED: 'ORDER RESTAURANT REJECTED',
    ORDER_RESTAURANT_CONFIRMED: 'ORDER RESTAURANT CONFIRMED'
};

module.exports = ResponseString;